### ISSUE TITLE
为什么Tab一定要设为8个而非4个？

### ISSUE THREAD

**Issue by HanderWei** [waylau/java-code-conventions#1]
非常不解，因为前面提到缩进是4个空格，为什么要将Tab设置为8个空格？

**Comment by waylau** [comment]
@HanderWei  这个规范应该从 C 语言规范而来。在不同的编辑器里tab的长度可能不一致，所以在一个编辑器里用tab设置缩进后，在其它编辑器里看可能缩进就乱了。 
空格不会出现这个问题，因为空格就占一个字符的位置。 而tab就是tab。
一般不建议用tab来代替空格，除非整个团队都有一致的开发工具或者编码格式文件。

我的理解是tab设为8个空格是为了更好的与4个空格相区别？

擦~我也不解，如果你整明白了记得告诉我。

实际项目中都是用tab（4个空格）开行的。哈哈

例外，推介看下 这个 http://bigc.at/tabs-vs-spaces.orz
