### ISSUE TITLE
关于第 4 章“缩进”的疑问

### ISSUE THREAD

**Issue by ghost** [waylau/java-code-conventions#6]
> 4 个空格常被作为缩进排版的一个单位。缩进的确切解释并未详细指定 (使用空格还是 tab)。Tab 一定要设置为 8 个空格 (而非 4 个)

我的理解：缩进还是使用 4 个空格，但是 Tab 要设置为 8 个空格。

这样对不？
![snip20170831_10](https://user-images.githubusercontent.com/29992491/29920951-70b6d6d0-8e82-11e7-935a-01cfd8f16a0d.png)

**Comment by waylau** [comment]
从整个章节的上下文看，这里的“缩进”是一种泛指，就是相对与上一行空几格的意思。
缩进有2中实现方式：

1. 打空格键
2. 打Tab建

不同的IED或者文本编辑器中，Tab的空格数是不同的，常见的有4格或者8格。所以，这个文档中，如果强调了使用 Tab 键来缩进，意味着空了8格。否则，直接说明空了几个格，不然，会产生歧义。
